export type ReferenceEntry = {
  code: string;
  framework: "ISO/IEC 27001:2022" | "NIST CSF 2.0" | "LGPD";
  title: string;
  text: string;
  sourceUrl: string;
  sourceLabel: string;
  contentType: "Resumo explicativo" | "Descrição oficial" | "Texto legal resumido";
};

const isoSource = "https://www.iso.org/standard/27001";
const nistSource = "https://www.nist.gov/cyberframework";
const lgpdSource = "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm";

const entries: ReferenceEntry[] = [
  { code: "A.5.2", framework: "ISO/IEC 27001:2022", title: "Papéis e responsabilidades de segurança da informação", text: "Orienta que papéis e responsabilidades de segurança sejam definidos e atribuídos de acordo com as necessidades da organização.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.15", framework: "ISO/IEC 27001:2022", title: "Controle de acesso", text: "Trata da definição e aplicação de regras para controlar o acesso físico e lógico às informações e aos ativos associados.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.17", framework: "ISO/IEC 27001:2022", title: "Informações de autenticação", text: "Orienta controlar a atribuição e a gestão de informações de autenticação por meio de um processo formal.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.18", framework: "ISO/IEC 27001:2022", title: "Direitos de acesso", text: "Trata da concessão, revisão, modificação e remoção de direitos de acesso conforme as regras de controle de acesso da organização.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.24", framework: "ISO/IEC 27001:2022", title: "Planejamento da gestão de incidentes", text: "Orienta preparar a gestão de incidentes de segurança por meio da definição, estabelecimento e comunicação de processos, papéis e responsabilidades.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.28", framework: "ISO/IEC 27001:2022", title: "Coleta de evidências", text: "Orienta a estabelecer procedimentos para identificar, coletar, adquirir e preservar evidências relacionadas a eventos de segurança.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.29", framework: "ISO/IEC 27001:2022", title: "Segurança da informação durante interrupções", text: "Orienta o planejamento para manter um nível apropriado de segurança da informação durante situações de interrupção.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.30", framework: "ISO/IEC 27001:2022", title: "Prontidão de TIC para continuidade de negócios", text: "Trata do planejamento, implementação, manutenção e teste da prontidão de tecnologia para suportar os objetivos de continuidade do negócio.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.31", framework: "ISO/IEC 27001:2022", title: "Requisitos legais, regulatórios e contratuais", text: "Orienta identificar, documentar e manter atualizados os requisitos legais, regulatórios e contratuais aplicáveis à segurança da informação.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.5.36", framework: "ISO/IEC 27001:2022", title: "Conformidade com políticas e normas", text: "Trata da revisão regular da conformidade com políticas, regras e normas de segurança da informação da organização.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.8", framework: "ISO/IEC 27001:2022", title: "Gestão de vulnerabilidades técnicas", text: "Trata da obtenção de informações sobre vulnerabilidades, avaliação da exposição e adoção de medidas apropriadas de tratamento.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.9", framework: "ISO/IEC 27001:2022", title: "Gestão de configuração", text: "Orienta estabelecer, documentar, implementar, monitorar e revisar configurações de hardware, software, serviços e redes.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.13", framework: "ISO/IEC 27001:2022", title: "Backup de informações", text: "Trata da manutenção e dos testes regulares de cópias de segurança de informações, software e sistemas conforme uma política definida.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.16", framework: "ISO/IEC 27001:2022", title: "Atividades de monitoramento", text: "Orienta monitorar redes, sistemas e aplicações quanto a comportamentos anômalos e avaliar potenciais incidentes de segurança.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.15", framework: "ISO/IEC 27001:2022", title: "Registro de eventos", text: "Orienta produzir, armazenar, proteger e analisar registros de atividades, exceções, falhas e outros eventos relevantes.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.20", framework: "ISO/IEC 27001:2022", title: "Segurança de redes", text: "Trata da proteção, gestão e controle de redes e dispositivos de rede para resguardar informações em sistemas e aplicações.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.22", framework: "ISO/IEC 27001:2022", title: "Segregação de redes", text: "Trata da separação de grupos de serviços de informação, usuários e sistemas nas redes da organização.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "A.8.24", framework: "ISO/IEC 27001:2022", title: "Uso de criptografia", text: "Orienta definir e implementar regras para o uso eficaz de criptografia, incluindo a gestão de chaves criptográficas.", sourceUrl: isoSource, sourceLabel: "ISO — ISO/IEC 27001:2022", contentType: "Resumo explicativo" },
  { code: "PR.AA", framework: "NIST CSF 2.0", title: "Gestão de identidade, autenticação e controle de acesso", text: "O acesso a ativos físicos e lógicos é limitado a usuários, serviços e hardware autorizados e gerenciado proporcionalmente ao risco avaliado de acesso não autorizado.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "PR.DS", framework: "NIST CSF 2.0", title: "Segurança de dados", text: "Os dados são gerenciados de forma consistente com a estratégia de risco da organização para proteger confidencialidade, integridade e disponibilidade.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "PR.PS", framework: "NIST CSF 2.0", title: "Segurança de plataformas", text: "Hardware, software e serviços de plataformas físicas e virtuais são gerenciados de forma consistente com a estratégia de risco para proteger sua confidencialidade, integridade e disponibilidade.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "PR.IR", framework: "NIST CSF 2.0", title: "Resiliência da infraestrutura tecnológica", text: "Arquiteturas de segurança são gerenciadas com a estratégia de risco da organização para proteger a confidencialidade, integridade, disponibilidade e resiliência dos ativos.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "DE.CM", framework: "NIST CSF 2.0", title: "Monitoramento contínuo", text: "Ativos são monitorados para encontrar anomalias, indicadores de comprometimento e outros eventos potencialmente adversos.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "DE.AE", framework: "NIST CSF 2.0", title: "Análise de eventos adversos", text: "Anomalias, indicadores de comprometimento e outros eventos potencialmente adversos são analisados para caracterizar os eventos e detectar incidentes de segurança cibernética.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "RC.RP", framework: "NIST CSF 2.0", title: "Execução do plano de recuperação", text: "Atividades de restauração são executadas para assegurar a disponibilidade operacional dos sistemas e serviços afetados por incidentes de segurança cibernética.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "GV.OC", framework: "NIST CSF 2.0", title: "Contexto organizacional", text: "Circunstâncias, missão, expectativas das partes interessadas e requisitos legais, regulatórios e contratuais que cercam decisões de risco são compreendidos.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "ID.IM", framework: "NIST CSF 2.0", title: "Melhoria", text: "Melhorias nos processos, procedimentos e atividades de gestão de risco são identificadas em todas as funções do CSF.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "ID.AM", framework: "NIST CSF 2.0", title: "Gestão de ativos", text: "Ativos que permitem à organização atingir objetivos de negócio são identificados e gerenciados de acordo com sua importância e com a estratégia de risco.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "ID.RA", framework: "NIST CSF 2.0", title: "Avaliação de riscos", text: "O risco de segurança cibernética para a organização, seus ativos e indivíduos é compreendido.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "GV.OV", framework: "NIST CSF 2.0", title: "Supervisão", text: "Resultados e desempenho das atividades de gestão de risco de segurança cibernética são usados para informar, melhorar e ajustar a estratégia de risco.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "GV.RR", framework: "NIST CSF 2.0", title: "Papéis, responsabilidades e autoridades", text: "Papéis, responsabilidades e autoridades de segurança cibernética são estabelecidos, comunicados, compreendidos e aplicados.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "RS.MA", framework: "NIST CSF 2.0", title: "Gestão de incidentes", text: "As respostas a incidentes de segurança cibernética detectados são gerenciadas de forma coordenada.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "RS.AN", framework: "NIST CSF 2.0", title: "Análise de incidentes", text: "Investigações são conduzidas para assegurar resposta eficaz e apoiar atividades de perícia e recuperação.", sourceUrl: nistSource, sourceLabel: "NIST Cybersecurity Framework 2.0", contentType: "Descrição oficial" },
  { code: "ART. 15", framework: "LGPD", title: "Término do tratamento de dados pessoais", text: "O tratamento termina quando sua finalidade é alcançada, os dados deixam de ser necessários, encerra-se o período de tratamento, há comunicação do titular ou determinação da autoridade nacional, observadas as hipóteses legais.", sourceUrl: lgpdSource, sourceLabel: "Lei nº 13.709/2018 — texto compilado", contentType: "Texto legal resumido" },
  { code: "ART. 46", framework: "LGPD", title: "Medidas de segurança", text: "Os agentes de tratamento devem adotar medidas técnicas e administrativas aptas a proteger dados pessoais contra acessos não autorizados e situações acidentais ou ilícitas de destruição, perda, alteração, comunicação ou tratamento inadequado ou ilícito.", sourceUrl: lgpdSource, sourceLabel: "Lei nº 13.709/2018 — texto compilado", contentType: "Texto legal resumido" },
  { code: "ART. 48", framework: "LGPD", title: "Comunicação de incidente de segurança", text: "O controlador deve comunicar à autoridade nacional e ao titular a ocorrência de incidente de segurança que possa acarretar risco ou dano relevante aos titulares, observando prazo e conteúdo definidos pela regulamentação.", sourceUrl: lgpdSource, sourceLabel: "Lei nº 13.709/2018 — texto compilado", contentType: "Texto legal resumido" },
  { code: "ART. 49", framework: "LGPD", title: "Estruturação segura dos sistemas", text: "Os sistemas utilizados para o tratamento de dados pessoais devem ser estruturados para atender aos requisitos de segurança, aos padrões de boas práticas e governança e aos princípios gerais previstos na LGPD.", sourceUrl: lgpdSource, sourceLabel: "Lei nº 13.709/2018 — texto compilado", contentType: "Texto legal resumido" },
  { code: "ART. 50", framework: "LGPD", title: "Boas práticas e governança", text: "Controladores e operadores podem formular regras de boas práticas e governança que estabeleçam organização, funcionamento, procedimentos, normas de segurança, padrões técnicos, obrigações, ações educativas, mecanismos internos de supervisão e mitigação de riscos.", sourceUrl: lgpdSource, sourceLabel: "Lei nº 13.709/2018 — texto compilado", contentType: "Texto legal resumido" },
];

export const normalizeReferenceCode = (code: string) => code.trim().toUpperCase().replace(/^ART\.\s*/, "ART. ");
export const referenceFor = (code: string) => {
  const normalized = normalizeReferenceCode(code);
  const exact = entries.find((entry) => entry.code === normalized);
  if (exact) return exact;
  const categoryCode = normalized.replace(/-\d+$/, "");
  const category = entries.find((entry) => entry.code === categoryCode);
  return category ? { ...category, code: normalized, title: `${category.title} — subcategoria ${normalized}` } : undefined;
};
