import pptxgen from "pptxgenjs";
import { pillars } from "../../assessment-data";
import { addPillarDetailSlides } from "../../ppt/pillar-detail";
import { addIsoExposureSlides } from "../../ppt/iso-exposures";
import { addNistExposureSlides } from "../../ppt/nist-exposures";
import { addLgpdExposureSlides } from "../../ppt/lgpd-exposures";
import { addVulnerabilitySummarySlides, type SoftwareForExport, type VulnerabilityForExport } from "../../ppt/vulnerability-summary";
import coverReference from "../../assets/ppt-cover-reference.jpg?inline";
import objectiveReference from "../../assets/ppt-objective-reference.jpg?inline";
import resilienceMessageReference from "../../assets/ppt-resilience-message-reference.jpg?inline";
import dataResilienceJourneyReference from "../../assets/ppt-data-resilience-journey-reference.jpg?inline";
import xtrAssessmentDividerReference from "../../assets/ppt-xtr-assessment-divider-reference.jpg?inline";
import diagnosisDashboardBackground from "../../assets/ppt-diagnosis-dashboard-background.jpg?inline";
import technicalAnalysisBlankReference from "../../assets/ppt-technical-analysis-blank-reference.jpg?inline";
import executiveAnalysisBlankReference from "../../assets/ppt-executive-analysis-blank-reference.jpg?inline";
import maturityByPillarDividerReference from "../../assets/ppt-maturity-by-pillar-divider-reference.jpg?inline";
import dataProtectionFoundationsReference from "../../assets/ppt-data-protection-foundations-reference.jpg?inline";
import replicationControlsReference from "../../assets/ppt-replication-controls-reference.jpg?inline";
import isolationComplianceReference from "../../assets/ppt-isolation-compliance-reference.jpg?inline";
import responseReadinessReference from "../../assets/ppt-response-readiness-reference.jpg?inline";
import governanceManagementReference from "../../assets/ppt-governance-management-reference.jpg?inline";
import vulnerabilitiesCriminalsDivider from "../../assets/ppt-vulnerabilities-criminals-divider.jpg?inline";
import vulnerabilityAnalysisBackground from "../../assets/ppt-vulnerability-analysis-background.jpg?inline";
import iso27001ExposuresDivider from "../../assets/ppt-iso-27001-exposures-divider.jpg?inline";
import isoExposuresBackground from "../../assets/ppt-iso-exposures-background.jpg?inline";
import nistExposuresDivider from "../../assets/ppt-nist-exposures-divider.jpg?inline";
import nistExposuresBackground from "../../assets/ppt-nist-exposures-background.jpg?inline";
import lgpdFindingsDivider from "../../assets/ppt-lgpd-findings-divider.jpg?inline";
import lgpdExposuresDivider from "../../assets/ppt-lgpd-exposures-divider.jpg?inline";
import conclusionsDivider from "../../assets/ppt-conclusions-divider.jpg?inline";
import nextStepsBlank from "../../assets/ppt-next-steps-blank.jpg?inline";
import continuityClosing from "../../assets/ppt-continuity-closing.jpg?inline";
import xtremeItClosing from "../../assets/ppt-xtreme-it-closing.jpg?inline";
import xtremeItLogo from "../../assets/xtreme-it-logo.png?inline";
import type { AssessmentObservation } from "../../observation-mapping";

type ExportPayload = { client: string; answers: Record<string, { score: number; note: string }>; isgAnswers?: Record<string, { score: number; note: string }>; pillarScores: number[]; totalScore: number; maturity: string; findings: Array<{ pillar: { name: string }; question: { title: string; iso: string; nist: string; lgpd: string }; score: number }>; software?: SoftwareForExport[]; vulnerabilities?: VulnerabilityForExport[]; observations?: AssessmentObservation[]; excludedFindingIds?: string[] };

const C = { bg: "05070D", panel: "111521", cyan: "1DDBE0", magenta: "EC39CB", white: "F5F7FB", muted: "8791A5", line: "283047", danger: "FF4D68" };
function title(slide: pptxgen.Slide, heading: string, sub = "") { slide.background = { color: C.bg }; slide.addText("XTREME IT", { x: .45, y: .24, w: 1.2, h: .2, fontFace: "Arial", fontSize: 8, bold: true, color: C.white }); slide.addText(heading, { x: .55, y: .62, w: 11.8, h: .42, fontFace: "Arial", fontSize: 23, bold: true, color: C.white, breakLine: false }); if (sub) slide.addText(sub, { x: .55, y: 1.04, w: 11.6, h: .22, fontFace: "Arial", fontSize: 8, color: C.muted }); slide.addShape("line", { x: .55, y: 1.34, w: 12.1, h: 0, line: { color: C.line, width: 1 } }); }
function maturityLabel(score: number) { return score <= 20 ? "Preocupante" : score <= 47 ? "Baixo" : score <= 61 ? "Intermediário" : score <= 74 ? "Avançado" : "Altamente Resiliente"; }
export async function POST(request: Request) {
  const data = await request.json() as ExportPayload;
  const generatedAt = new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date());
  const generatedMonthYear = new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", month: "long", year: "numeric" }).format(new Date());
  const pptx = new pptxgen(); pptx.layout = "LAYOUT_WIDE"; pptx.author = "Xtreme IT"; pptx.subject = "XTR Assessment"; pptx.title = `Assessment de Resiliência de Dados — ${data.client}`; pptx.company = "Xtreme IT"; pptx.lang = "pt-BR"; pptx.theme = { headFontFace: "Arial", bodyFontFace: "Arial", lang: "pt-BR" };
  let slide = pptx.addSlide();
  slide.background = { color: "000106" };
  slide.addImage({ data: coverReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide.addImage({ data: xtremeItLogo, x: 10.62, y: .48, w: 2.32, h: .59 });
  slide.addShape("rect", { x: 11.5, y: 6.8, w: 1.55, h: .55, fill: { color: "03060D" }, line: { transparency: 100 } });
  slide.addText(generatedAt, { x: 11.55, y: 6.89, w: 1.36, h: .22, fontFace: "Raleway", fontSize: 10, color: "D8D8D8", align: "right", margin: 0, breakLine: false });
  slide.addShape("line", { x: 12.05, y: 7.22, w: .43, h: 0, line: { color: "1DDBE0", width: 1.1 } });
  slide.addShape("line", { x: 12.48, y: 7.22, w: .43, h: 0, line: { color: "EC39CB", width: 1.1 } });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: objectiveReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: resilienceMessageReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "00020B" };
  slide.addImage({ data: dataResilienceJourneyReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: xtrAssessmentDividerReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: diagnosisDashboardBackground, x: 0, y: 0, w: 13.334, h: 7.5 });
  const maturityColors = ["FF4D68", "FF8A4C", "FFD166", "1DDBE0", "35D999"];
  const currentMaturityColor = data.totalScore <= 20 ? maturityColors[0] : data.totalScore <= 47 ? maturityColors[1] : data.totalScore <= 61 ? maturityColors[2] : data.totalScore <= 74 ? maturityColors[3] : maturityColors[4];
  const maturitySummary = data.totalScore <= 20 ? "Exposição elevada e baixa previsibilidade de recuperação." : data.totalScore <= 47 ? "Controles básicos existem, mas há gaps relevantes de resiliência." : data.totalScore <= 61 ? "Capacidades implementadas com oportunidades importantes de evolução." : data.totalScore <= 74 ? "Boa maturidade, com controles consistentes e gaps pontuais." : "Proteção integrada, testada e governada de forma contínua.";
  slide.addShape("roundRect", { x: .55, y: 2.65, w: 2.45, h: 3.83, rectRadius: .08, fill: { color: "080B12", transparency: 8 }, line: { color: "263044", width: 1 } });
  slide.addText("SCORE DE MATURIDADE", { x: .78, y: 2.92, w: 2, h: .25, fontFace: "Arial", fontSize: 10, bold: true, color: "AAB2C2", align: "center", margin: 0 });
  slide.addShape("ellipse", { x: 1.04, y: 3.28, w: 1.47, h: 1.47, fill: { color: "05070D" }, line: { color: currentMaturityColor, width: 4 } });
  slide.addText(String(data.totalScore), { x: 1.04, y: 3.55, w: 1.47, h: .48, fontFace: "Arial", fontSize: 34, bold: true, color: currentMaturityColor, align: "center", valign: "mid", margin: 0, breakLine: false });
  slide.addText("/100", { x: 1.04, y: 4.08, w: 1.47, h: .16, fontFace: "Arial", fontSize: 8, color: "AAB2C2", align: "center", margin: 0, breakLine: false });
  slide.addText(data.maturity.toUpperCase(), { x: .76, y: 4.88, w: 2.02, h: .3, fontFace: "Arial", fontSize: 12, bold: true, color: currentMaturityColor, align: "center", margin: 0, breakLine: false });
  slide.addText(maturitySummary, { x: .78, y: 5.25, w: 1.98, h: .48, fontFace: "Arial", fontSize: 7.2, color: "D8DCE6", align: "center", valign: "mid", margin: .02, breakLine: false });
  slide.addText(data.client || "Assessment em andamento", { x: .76, y: 5.85, w: 2.02, h: .17, fontFace: "Arial", fontSize: 7.5, color: "AAB2C2", align: "center", margin: 0, breakLine: false });
  slide.addText(generatedMonthYear.charAt(0).toUpperCase() + generatedMonthYear.slice(1), { x: .76, y: 6.09, w: 2.02, h: .16, fontFace: "Arial", fontSize: 7, color: "8791A5", align: "center", margin: 0, breakLine: false });
  slide.addShape("roundRect", { x: 3.18, y: 2.65, w: 9.56, h: 1.42, rectRadius: .06, fill: { color: "080B12", transparency: 8 }, line: { color: "263044", width: 1 } });
  slide.addText("LEGENDA DOS NÍVEIS DE MATURIDADE", { x: 3.45, y: 2.86, w: 4.2, h: .2, fontFace: "Arial", fontSize: 9, bold: true, color: "AAB2C2", margin: 0 });
  const maturityRanges = [["PREOCUPANTE", "Até 20 pontos"], ["BAIXO", "21 a 47 pontos"], ["INTERMEDIÁRIO", "48 a 61 pontos"], ["AVANÇADO", "62 a 74 pontos"], ["ALTAMENTE RESILIENTE", "Acima de 75 pontos"]];
  maturityRanges.forEach(([label, range], index) => { const x = 3.45 + index * 1.82; slide.addShape("roundRect", { x, y: 3.21, w: 1.68, h: .58, rectRadius: .04, fill: { color: maturityColors[index], transparency: data.maturity.toUpperCase() === label ? 72 : 90 }, line: { color: maturityColors[index], width: data.maturity.toUpperCase() === label ? 2 : .8 } }); slide.addText(label, { x: x + .08, y: 3.31, w: 1.52, h: .14, fontFace: "Arial", fontSize: label.length > 14 ? 6.2 : 7.2, bold: true, color: maturityColors[index], align: "center", margin: 0, breakLine: false }); slide.addText(range, { x: x + .08, y: 3.5, w: 1.52, h: .13, fontFace: "Arial", fontSize: 6.3, color: "D8DCE6", align: "center", margin: 0, breakLine: false }); });
  slide.addShape("roundRect", { x: 3.18, y: 4.28, w: 9.56, h: 2.2, rectRadius: .06, fill: { color: "080B12", transparency: 5 }, line: { color: "263044", width: 1 } });
  slide.addText("RESULTADO POR PILAR", { x: 3.45, y: 4.49, w: 3.2, h: .2, fontFace: "Arial", fontSize: 9, bold: true, color: "AAB2C2", margin: 0 });
  pillars.forEach((p, i) => { const y = 4.85 + i * .3; const pillarColor = p.color.replace("#", "").toUpperCase(); const score = data.pillarScores[i] ?? 0; slide.addText(p.name, { x: 3.45, y, w: 2.65, h: .17, fontFace: "Arial", fontSize: 7.4, color: "F5F7FB", margin: 0, breakLine: false }); slide.addShape("roundRect", { x: 6.25, y: y + .02, w: 5.35, h: .1, rectRadius: .02, fill: { color: "202637" }, line: { transparency: 100 } }); if (score > 0) slide.addShape("roundRect", { x: 6.25, y: y + .02, w: 5.35 * score / 20, h: .1, rectRadius: .02, fill: { color: pillarColor }, line: { transparency: 100 } }); slide.addText(`${score}/20`, { x: 11.82, y: y - .02, w: .58, h: .17, fontFace: "Arial", fontSize: 7.5, bold: true, color: pillarColor, align: "right", margin: 0, breakLine: false }); });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: technicalAnalysisBlankReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: executiveAnalysisBlankReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: maturityByPillarDividerReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: dataProtectionFoundationsReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  addPillarDetailSlides(pptx, pillars[0], 0, data.answers, xtremeItLogo);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: replicationControlsReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  addPillarDetailSlides(pptx, pillars[1], 1, data.answers, xtremeItLogo);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: isolationComplianceReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  addPillarDetailSlides(pptx, pillars[2], 2, data.answers, xtremeItLogo);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: responseReadinessReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  addPillarDetailSlides(pptx, pillars[3], 3, data.answers, xtremeItLogo);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: governanceManagementReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  addPillarDetailSlides(pptx, pillars[4], 4, data.answers, xtremeItLogo);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: vulnerabilitiesCriminalsDivider, x: 0, y: 0, w: 13.334, h: 7.5 });
  addVulnerabilitySummarySlides(pptx, data.software ?? [], data.vulnerabilities ?? [], vulnerabilityAnalysisBackground);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: iso27001ExposuresDivider, x: 0, y: 0, w: 13.334, h: 7.5 });
  addIsoExposureSlides(pptx, data.answers ?? {}, data.vulnerabilities ?? [], isoExposuresBackground, data.excludedFindingIds ?? [], data.observations ?? []);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: nistExposuresDivider, x: 0, y: 0, w: 13.334, h: 7.5 });
  addNistExposureSlides(pptx, data.answers ?? {}, data.vulnerabilities ?? [], nistExposuresBackground, data.excludedFindingIds ?? [], data.observations ?? []);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: lgpdFindingsDivider, x: 0, y: 0, w: 13.334, h: 7.5 });
  addLgpdExposureSlides(pptx, data.answers ?? {}, data.vulnerabilities ?? [], lgpdExposuresDivider, data.excludedFindingIds ?? [], data.observations ?? []);
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: conclusionsDivider, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: nextStepsBlank, x: 0, y: 0, w: 13.334, h: 7.5 });
  const projectedPillarScores = pillars.map((pillar) => pillar.questions.reduce((sum, question) => sum + Math.max(0, Math.min(question.max, data.isgAnswers?.[question.id]?.score ?? data.answers?.[question.id]?.score ?? 0)), 0));
  const projectedTotalScore = projectedPillarScores.reduce((sum, score) => sum + score, 0);
  const projectedColor = projectedTotalScore <= 20 ? maturityColors[0] : projectedTotalScore <= 47 ? maturityColors[1] : projectedTotalScore <= 61 ? maturityColors[2] : projectedTotalScore <= 74 ? maturityColors[3] : maturityColors[4];
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: nextStepsBlank, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide.addShape("rect", { x: .35, y: .67, w: 7.85, h: 1.36, fill: { color: "141416" }, line: { transparency: 100 } });
  slide.addText("Evolução de Maturidade", { x: .45, y: .94, w: 7.45, h: .48, fontFace: "Raleway", fontSize: 31, bold: true, color: C.white, margin: 0, breakLine: false });
  slide.addText("Impacto esperado com Serviços Gerenciados", { x: .46, y: 1.56, w: 6.8, h: .25, fontFace: "Raleway", fontSize: 13, color: "E0E2E8", margin: 0, breakLine: false });
  slide.addShape("roundRect", { x: .55, y: 2.45, w: 3.15, h: 3.72, rectRadius: .06, fill: { color: "080B12", transparency: 5 }, line: { color: "3A284D", width: 1 } });
  slide.addText("EVOLUÇÃO DO SCORE", { x: .8, y: 2.72, w: 2.65, h: .2, fontFace: "Arial", fontSize: 9, bold: true, color: "AAB2C2", align: "center", margin: 0 });
  slide.addShape("ellipse", { x: .83, y: 3.18, w: 1.05, h: 1.05, fill: { color: "05070D" }, line: { color: currentMaturityColor, width: 3 } });
  slide.addText(String(data.totalScore), { x: .83, y: 3.41, w: 1.05, h: .3, fontFace: "Arial", fontSize: 23, bold: true, color: currentMaturityColor, align: "center", margin: 0, breakLine: false });
  slide.addText("ATUAL", { x: .83, y: 4.34, w: 1.05, h: .18, fontFace: "Arial", fontSize: 7, bold: true, color: "AAB2C2", align: "center", margin: 0 });
  slide.addText("→", { x: 1.91, y: 3.49, w: .45, h: .26, fontFace: "Arial", fontSize: 18, bold: true, color: C.cyan, align: "center", margin: 0 });
  slide.addShape("ellipse", { x: 2.38, y: 3.18, w: 1.05, h: 1.05, fill: { color: "05070D" }, line: { color: projectedColor, width: 3 } });
  slide.addText(String(projectedTotalScore), { x: 2.38, y: 3.41, w: 1.05, h: .3, fontFace: "Arial", fontSize: 23, bold: true, color: projectedColor, align: "center", margin: 0, breakLine: false });
  slide.addText("COM ISG", { x: 2.38, y: 4.34, w: 1.05, h: .18, fontFace: "Arial", fontSize: 7, bold: true, color: C.cyan, align: "center", margin: 0 });
  slide.addText(`${maturityLabel(data.totalScore)}  →  ${maturityLabel(projectedTotalScore)}`, { x: .78, y: 4.82, w: 2.7, h: .28, fontFace: "Arial", fontSize: 10, bold: true, color: C.white, align: "center", margin: 0, breakLine: false });
  slide.addShape("roundRect", { x: 1.12, y: 5.31, w: 2.03, h: .45, rectRadius: .06, fill: { color: "0A3028" }, line: { color: "35D999", width: 1 } });
  slide.addText(`+${Math.max(0, projectedTotalScore - data.totalScore)} PONTOS`, { x: 1.2, y: 5.44, w: 1.87, h: .16, fontFace: "Arial", fontSize: 8.5, bold: true, color: "35D999", align: "center", margin: 0, breakLine: false });
  slide.addShape("roundRect", { x: 3.95, y: 2.45, w: 8.83, h: 3.72, rectRadius: .06, fill: { color: "080B12", transparency: 5 }, line: { color: "263044", width: 1 } });
  slide.addText("MATURIDADE POR PILAR", { x: 4.25, y: 2.69, w: 2.7, h: .16, fontFace: "Raleway", fontSize: 7.2, charSpacing: 1.3, color: "8791A5", margin: 0, breakLine: false });
  slide.addText("Equilíbrio de capacidades", { x: 4.25, y: 2.91, w: 3.6, h: .27, fontFace: "Raleway", fontSize: 14, bold: true, color: C.white, margin: 0, breakLine: false });
  slide.addShape("ellipse", { x: 10.37, y: 2.78, w: .1, h: .1, fill: { color: C.magenta }, line: { transparency: 100 } });
  slide.addText("ATUAL", { x: 10.52, y: 2.75, w: .62, h: .16, fontFace: "Raleway", fontSize: 6.5, color: "AAB2C2", margin: 0 });
  slide.addShape("ellipse", { x: 11.3, y: 2.78, w: .1, h: .1, fill: { color: C.cyan }, line: { transparency: 100 } });
  slide.addText("COM ISG", { x: 11.45, y: 2.75, w: .8, h: .16, fontFace: "Raleway", fontSize: 6.5, color: "AAB2C2", margin: 0 });
  slide.addChart(pptx.ChartType.radar, [
    { name: "Com ISG", labels: pillars.map((pillar) => pillar.name), values: projectedPillarScores },
    { name: "Atual", labels: pillars.map((pillar) => pillar.name), values: data.pillarScores.map((score) => score ?? 0) },
  ], { x: 5.18, y: 3.18, w: 6.25, h: 2.72, radarStyle: "filled", chartColors: [C.cyan, C.magenta], chartColorsOpacity: 48, showLegend: false, showTitle: false, showValue: false, showCatName: false, catAxisLabelFontFace: "Raleway", catAxisLabelFontSize: 7.5, catAxisLabelColor: "98A2B7", valAxisMinVal: 0, valAxisMaxVal: 20, valAxisMajorUnit: 5, valAxisLabelColor: "080B12", valAxisLabelFontSize: 1, valAxisLineColor: "30384D", valAxisLineSize: 1, valGridLine: { color: "30384D", width: 1 }, showCatAxisTitle: false, showValAxisTitle: false, showLabel: false, showSerName: false, lineSize: 1.5, showMarker: false, showBorder: false });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: continuityClosing, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: xtremeItClosing, x: 0, y: 0, w: 13.334, h: 7.5 });
  const output = await pptx.write({ outputType: "arraybuffer" });
  return new Response(output as ArrayBuffer, { headers: { "content-type": "application/vnd.openxmlformats-officedocument.presentationml.presentation", "content-disposition": `attachment; filename="XTR-Assessment.pptx"` } });
}
