import pptxgen from "pptxgenjs";
import { pillars } from "../../assessment-data";
import coverReference from "../../assets/ppt-cover-reference.png?inline";
import objectiveReference from "../../assets/ppt-objective-reference.png?inline";
import resilienceMessageReference from "../../assets/ppt-resilience-message-reference.png?inline";
import dataResilienceJourneyReference from "../../assets/ppt-data-resilience-journey-reference.png?inline";
import xtrAssessmentDividerReference from "../../assets/ppt-xtr-assessment-divider-reference.jpg?inline";
import diagnosisDashboardBackground from "../../assets/ppt-diagnosis-dashboard-background.jpg?inline";
import xtremeItLogo from "../../assets/xtreme-it-logo.png?inline";

type ExportPayload = { client: string; answers: Record<string, { score: number; note: string }>; pillarScores: number[]; totalScore: number; maturity: string; findings: Array<{ pillar: { name: string }; question: { title: string; iso: string; nist: string; lgpd: string }; score: number }> };

const C = { bg: "05070D", panel: "111521", cyan: "1DDBE0", magenta: "EC39CB", white: "F5F7FB", muted: "8791A5", line: "283047", danger: "FF4D68" };
function title(slide: pptxgen.Slide, heading: string, sub = "") { slide.background = { color: C.bg }; slide.addText("XTREME IT", { x: .45, y: .24, w: 1.2, h: .2, fontFace: "Arial", fontSize: 8, bold: true, color: C.white }); slide.addText(heading, { x: .55, y: .62, w: 11.8, h: .42, fontFace: "Arial", fontSize: 23, bold: true, color: C.white, breakLine: false }); if (sub) slide.addText(sub, { x: .55, y: 1.04, w: 11.6, h: .22, fontFace: "Arial", fontSize: 8, color: C.muted }); slide.addShape("line", { x: .55, y: 1.34, w: 12.1, h: 0, line: { color: C.line, width: 1 } }); }
export async function POST(request: Request) {
  const data = await request.json() as ExportPayload;
  const generatedAt = new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date());
  const generatedMonthYear = new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", month: "long", year: "numeric" }).format(new Date());
  const pptx = new pptxgen(); pptx.layout = "LAYOUT_WIDE"; pptx.author = "Xtreme IT"; pptx.subject = "XTR Assessment"; pptx.title = `Assessment de Resiliência de Dados — ${data.client}`; pptx.company = "Xtreme IT"; pptx.lang = "pt-BR"; pptx.theme = { headFontFace: "Arial", bodyFontFace: "Arial", lang: "pt-BR" };
  let slide = pptx.addSlide();
  slide.background = { color: "000106" };
  slide.addImage({ data: coverReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide.addImage({ data: xtremeItLogo, x: 10.62, y: .48, w: 2.32, h: .59 });
  slide.addShape("rect", { x: 11.5, y: 6.8, w: 1.55, h: .55, fill: { color: "03060D" }, line: { transparency: 100 } });
  slide.addText(generatedAt, { x: 11.55, y: 6.89, w: 1.36, h: .22, fontFace: "Raleway", fontSize: 10, color: "D8D8D8", align: "right", margin: 0, breakLine: false });
  slide.addShape("line", { x: 12.05, y: 7.22, w: .43, h: 0, line: { color: "1DDBE0", width: 1.1 } });
  slide.addShape("line", { x: 12.48, y: 7.22, w: .43, h: 0, line: { color: "EC39CB", width: 1.1 } });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: objectiveReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: resilienceMessageReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "00020B" };
  slide.addImage({ data: dataResilienceJourneyReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: xtrAssessmentDividerReference, x: 0, y: 0, w: 13.334, h: 7.5 });
  slide = pptx.addSlide();
  slide.background = { color: "000000" };
  slide.addImage({ data: diagnosisDashboardBackground, x: 0, y: 0, w: 13.334, h: 7.5 });
  const maturityColors = ["FF4D68", "FF8A4C", "FFD166", "1DDBE0", "35D999"];
  const currentMaturityColor = data.totalScore <= 20 ? maturityColors[0] : data.totalScore <= 47 ? maturityColors[1] : data.totalScore <= 61 ? maturityColors[2] : data.totalScore <= 74 ? maturityColors[3] : maturityColors[4];
  const maturitySummary = data.totalScore <= 20 ? "Exposição elevada e baixa previsibilidade de recuperação." : data.totalScore <= 47 ? "Controles básicos existem, mas há gaps relevantes de resiliência." : data.totalScore <= 61 ? "Capacidades implementadas com oportunidades importantes de evolução." : data.totalScore <= 74 ? "Boa maturidade, com controles consistentes e gaps pontuais." : "Proteção integrada, testada e governada de forma contínua.";
  const maturityRanges = [["PREOCUPANTE", "Até 20 pontos"], ["BAIXO", "21 a 47 pontos"], ["INTERMEDIÁRIO", "48 a 61 pontos"], ["AVANÇADO", "62 a 74 pontos"], ["ALTAMENTE RESILIENTE", "Acima de 75 pontos"]];
  const maturityDescriptions = ["Vulnerabilidades críticas e alto risco de indisponibilidade.", "Controles básicos com falhas relevantes e risco operacional.", "Controles parciais com melhorias necessárias para maior resiliência.", "Boas práticas consolidadas e baixo risco residual.", "Ambiente robusto, otimizado e preparado para responder a incidentes."];
  slide.addShape("roundRect", { x: .42, y: 2.28, w: 3.18, h: 3.08, rectRadius: .08, fill: { color: "050912", transparency: 3 }, line: { color: currentMaturityColor, width: 1.2 } });
  slide.addShape("line", { x: .64, y: 2.47, w: 2.74, h: 0, line: { color: "394154", width: .8 } });
  slide.addText("◈", { x: .62, y: 2.42, w: .45, h: .38, fontFace: "Arial", fontSize: 20, bold: true, color: currentMaturityColor, align: "center", margin: 0 });
  slide.addText("DASHBOARD DE MATURIDADE", { x: 1.05, y: 2.43, w: 2.05, h: .15, fontFace: "Arial", fontSize: 6.5, color: "D8DCE6", margin: 0, breakLine: false });
  slide.addText("BACKUP SECURITY", { x: 1.05, y: 2.62, w: 2.05, h: .22, fontFace: "Arial", fontSize: 11, bold: true, color: "F5F7FB", margin: 0, breakLine: false });
  slide.addText("NÍVEL DE MATURIDADE", { x: .72, y: 2.95, w: 2.58, h: .16, fontFace: "Arial", fontSize: 7.3, color: "D8DCE6", align: "center", margin: 0 });
  slide.addText(data.maturity, { x: .7, y: 3.14, w: 2.62, h: .3, fontFace: "Arial", fontSize: 18, bold: true, color: currentMaturityColor, align: "center", margin: 0, breakLine: false });
  slide.addText(maturitySummary, { x: .76, y: 3.46, w: 2.5, h: .22, fontFace: "Arial", fontSize: 6, color: "D8DCE6", align: "center", valign: "mid", margin: 0, breakLine: false });
  slide.addShape("ellipse", { x: 1.16, y: 3.72, w: 1.7, h: 1.2, fill: { color: "060A12", transparency: 3 }, line: { color: "252C38", width: 9 } });
  slide.addShape("ellipse", { x: 1.26, y: 3.81, w: 1.5, h: 1.02, fill: { color: "060A12" }, line: { color: currentMaturityColor, width: 3 } });
  slide.addText(String(data.totalScore), { x: 1.26, y: 3.98, w: 1.5, h: .42, fontFace: "Arial", fontSize: 31, bold: true, color: "F5F7FB", align: "center", valign: "mid", margin: 0, breakLine: false });
  slide.addText("/100", { x: 1.26, y: 4.45, w: 1.5, h: .16, fontFace: "Arial", fontSize: 9, color: "AAB2C2", align: "center", margin: 0 });
  slide.addShape("roundRect", { x: .68, y: 4.96, w: 2.66, h: .25, rectRadius: .04, fill: { color: "151B27" }, line: { transparency: 100 } });
  slide.addText(`${data.client || "Assessment em andamento"}  •  ${generatedMonthYear.charAt(0).toUpperCase() + generatedMonthYear.slice(1)}`, { x: .8, y: 5.02, w: 2.42, h: .12, fontFace: "Arial", fontSize: 6.2, color: "D8DCE6", align: "center", margin: 0, breakLine: false });
  slide.addShape("roundRect", { x: 3.72, y: 2.28, w: 9.2, h: 3.08, rectRadius: .08, fill: { color: "050912", transparency: 3 }, line: { color: "1DDBE0", width: 1.1 } });
  slide.addText("▣", { x: 3.98, y: 2.47, w: .4, h: .3, fontFace: "Arial", fontSize: 16, bold: true, color: "EC39CB", align: "center", margin: 0 });
  slide.addText("NÍVEL DE MATURIDADE POR PILAR", { x: 4.45, y: 2.49, w: 4.7, h: .24, fontFace: "Arial", fontSize: 13, color: "F5F7FB", margin: 0, breakLine: false });
  slide.addShape("line", { x: 3.98, y: 2.82, w: 8.66, h: 0, line: { color: "394154", width: .8 } });
  pillars.forEach((p, i) => { const y = 2.94 + i * .46; const pillarColor = p.color.replace("#", "").toUpperCase(); const score = data.pillarScores[i] ?? 0; slide.addShape("ellipse", { x: 4.02, y, w: .34, h: .34, fill: { color: pillarColor, transparency: 84 }, line: { color: pillarColor, width: 1 } }); slide.addText(p.icon, { x: 4.02, y: y + .07, w: .34, h: .14, fontFace: "Arial", fontSize: 7, color: pillarColor, align: "center", margin: 0 }); slide.addShape("ellipse", { x: 4.48, y: y + .02, w: .32, h: .32, fill: { color: pillarColor, transparency: 76 }, line: { transparency: 100 } }); slide.addText(String(i + 1), { x: 4.48, y: y + .07, w: .32, h: .14, fontFace: "Arial", fontSize: 9, bold: true, color: pillarColor, align: "center", margin: 0 }); slide.addText(p.name, { x: 4.98, y: y + .01, w: 2.06, h: .31, fontFace: "Arial", fontSize: 7.2, color: "F5F7FB", valign: "mid", margin: 0, breakLine: false }); slide.addShape("roundRect", { x: 7.12, y: y + .08, w: 4.45, h: .13, rectRadius: .03, fill: { color: "202637" }, line: { transparency: 100 } }); if (score > 0) slide.addShape("roundRect", { x: 7.12, y: y + .08, w: 4.45 * score / 20, h: .13, rectRadius: .03, fill: { color: pillarColor }, line: { transparency: 100 } }); slide.addText("0", { x: 7.12, y: y + .25, w: .25, h: .1, fontFace: "Arial", fontSize: 5.5, color: "8791A5", margin: 0 }); slide.addText("10", { x: 9.22, y: y + .25, w: .25, h: .1, fontFace: "Arial", fontSize: 5.5, color: "8791A5", align: "center", margin: 0 }); slide.addText("20", { x: 11.32, y: y + .25, w: .25, h: .1, fontFace: "Arial", fontSize: 5.5, color: "8791A5", align: "right", margin: 0 }); slide.addShape("roundRect", { x: 11.86, y: y + .03, w: .72, h: .27, rectRadius: .08, fill: { color: pillarColor, transparency: 12 }, line: { transparency: 100 } }); slide.addText(`${score}/20`, { x: 11.86, y: y + .08, w: .72, h: .14, fontFace: "Arial", fontSize: 8.5, bold: true, color: "05070D", align: "center", margin: 0, breakLine: false }); if (i < pillars.length - 1) slide.addShape("line", { x: 3.98, y: y + .41, w: 8.66, h: 0, line: { color: "202637", width: .6 } }); });
  maturityRanges.forEach(([label, range], index) => { const x = .42 + index * 2.5; const active = data.maturity.toUpperCase() === label; slide.addShape("roundRect", { x, y: 5.55, w: 2.38, h: 1.42, rectRadius: .06, fill: { color: active ? maturityColors[index] : "050912", transparency: active ? 84 : 8 }, line: { color: maturityColors[index], width: active ? 2 : 1 } }); slide.addText(label, { x: x + .18, y: 5.74, w: 2.02, h: .18, fontFace: "Arial", fontSize: label.length > 14 ? 7.2 : 8, bold: true, color: maturityColors[index], margin: 0, breakLine: false }); slide.addText(maturityDescriptions[index], { x: x + .18, y: 6.03, w: 2.02, h: .45, fontFace: "Arial", fontSize: 6.4, color: "D8DCE6", valign: "top", margin: 0, breakLine: false }); slide.addText(range, { x: x + .18, y: 6.66, w: 2.02, h: .15, fontFace: "Arial", fontSize: 7.2, bold: true, color: maturityColors[index], margin: 0, breakLine: false }); });
  pillars.forEach((pillar, pIndex) => { slide = pptx.addSlide(); title(slide, pillar.name, `Maturidade e riscos do negócio • ${data.pillarScores[pIndex]}/20 pontos`); const rows = pillar.questions.map((q) => [{ text: q.title, options: { bold: true, color: C.white } }, { text: `${data.answers[q.id]?.score ?? 0}/${q.max}`, options: { bold: true, color: C.cyan, align: "center" as const } }, { text: data.answers[q.id]?.note || q.risk, options: { color: C.muted } }]); slide.addTable([[{ text: "CRITÉRIO", options: { bold: true } }, { text: "NOTA", options: { bold: true } }, { text: "EVIDÊNCIA / EXPOSIÇÃO", options: { bold: true } }], ...rows], { x: .62, y: 1.58, w: 12.05, h: 4.8, border: { type: "solid", color: C.line, width: .5 }, fill: C.panel, color: C.white, fontFace: "Arial", fontSize: 10, rowH: .62, colW: [3.4, .8, 7.85], margin: .12, breakLine: false, autoFit: false }); });
  const chunks = Array.from({ length: Math.ceil(data.findings.length / 7) }, (_, i) => data.findings.slice(i * 7, i * 7 + 7));
  for (const [index, chunk] of chunks.entries()) { slide = pptx.addSlide(); title(slide, "Exposições ISO/IEC 27001 • NIST • LGPD", `Potenciais riscos em recuperação e continuidade ${index + 1}/${chunks.length}`); const rows = chunk.map((f, i) => [String(index * 7 + i + 1).padStart(2, "0"), f.question.title, f.question.iso, f.question.nist, f.question.lgpd]); slide.addTable([["#", "RISCO / GAP MAPEADO", "ISO 27001", "NIST CSF", "LGPD"], ...rows], { x: .62, y: 1.58, w: 12.05, h: 4.9, border: { type: "solid", color: C.line, width: .5 }, fill: C.panel, color: C.white, fontFace: "Arial", fontSize: 9, rowH: .58, colW: [.55, 6.2, 1.6, 1.6, 2.1], margin: .1, bold: false }); }
  slide = pptx.addSlide(); title(slide, "Conclusões e Próximos Passos", "Transformar risco em continuidade operacional"); slide.addText("A prioridade é reduzir as exposições críticas, comprovar a recuperabilidade e estabelecer uma governança contínua para proteção de dados.", { x: .75, y: 1.75, w: 11.4, h: .7, fontSize: 20, bold: true, color: C.white, breakLine: false }); const top = data.findings.slice(0, 5); top.forEach((f, i) => { slide.addText(String(i + 1).padStart(2, "0"), { x: .85, y: 2.8 + i * .58, w: .45, h: .25, fontSize: 9, bold: true, color: C.cyan }); slide.addText(f.question.title, { x: 1.4, y: 2.75 + i * .58, w: 10.5, h: .3, fontSize: 12, color: C.white }); }); slide.addText("Este material apresenta exposições potenciais e não constitui parecer jurídico ou certificação de conformidade.", { x: .75, y: 6.65, w: 11.5, h: .25, fontSize: 7, color: C.muted });
  const output = await pptx.write({ outputType: "arraybuffer" });
  return new Response(output as ArrayBuffer, { headers: { "content-type": "application/vnd.openxmlformats-officedocument.presentationml.presentation", "content-disposition": `attachment; filename="XTR-Assessment.pptx"` } });
}
